Name = "Steven"
print("Hello, " + "Steven")
print("Welcome to the Mad Libs game, " + Name + "!")
print( "this is my updated version!" )
print("Let's create a fun story together.")
print("Please provide the following words to fill in the blanks:")
adjective1 = input("Adjective: ")
adjective2 = input("Another adjective: ")
noun1 = input("Noun: ")
noun2 = input("Another noun: ")
verb1 = input("Verb: ")